config/routes.rb
Rails.application.routes.draw do

  resources :chapters
  resources :lessons
  resources :sections
  root 'chapters#show', id: 1
  devise_for :users
  resources :users
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
  has_many :sections
  has_many :lessons
end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
  belongs_to :section
  belongs_to :chapter

  def next
    if (self == Lesson.last)
      Lesson.first
    else
      next_lesson = Lesson.where("id > (?)", self.id).first
    end
  end
  def previous
    if (self != Lesson.first)
      Lesson.where("id < (?)", self.id).last
    else
      Lesson.last
    end
  end
end

app/models/section.rb
class Section < ActiveRecord::Base
  has_many :lessons
  belongs_to :chapter
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController
  def index
    @chapters = Chapter.all
  end

  def show
    @chapter = Chapter.find(params[:id])
  end

end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :find_lesson, except: [:create, :new, :index]
  def index
    @lessons = Lesson.all
  end

  def new
    @lesson = Lesson.new
  end

  def create
    @section = Section.find(params['lesson']['section_id'])
    @lesson = @section.lessons.new(lesson_params)
    @lesson.number = Lesson.all.length
    if @lesson.save
      redirect_to section_path(@lesson.section)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @lesson.update(lesson_params)
      redirect_to lesson_path(@lesson)
    else
      render :edit
    end
  end

  def destroy
    @lesson.destroy
    redirect_to chapter_path(1)
  end

  private
  def find_lesson
    @lesson = Lesson.find(params[:id])
  end
  def lesson_params
    params.require(:lesson).permit(:title, :content)
  end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :find_section, except: [:index, :create, :new]
  def new
    @section = Section.new
  end

  def index
    @sections = Section.all
  end

  def show
  end

  def create
    @chapter = Chapter.find(1)
    @section = @chapter.sections.new(section_params)
    if @section.save
      redirect_to section_path(@section)
    else
      render :new
    end
  end

  def destroy
    @section.destroy
    redirect_to chapter_path(1)
  end

  private
  def find_section
    @section = Section.find(params[:id])
  end
  def section_params
    params.require(:section).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chapters/index.html.erb
<h1>Learn How to Program</h1>

<ul>
  <% @chapters.sections.each do |section| %>
    <li><%= section.name %></li>
      <ul>
        <% section.lessons.each do |lesson| %>
          <li><%= lesson.title %></li>
        <% end %>
      </ul>
  <% end %>
</ul>

app/views/chapters/show.html.erb
<div class="row">
  <ul>
    <% @chapter.sections.each do |section| %>
      <div class="col-md-6 panel panel-default">
        <li class="panel-heading"><%= link_to section.name, section_path(section) %></li>
          <ul>
            <% section.lessons.each do |lesson| %>
              <li class="panel-body"><%= link_to lesson.title, lesson_path(lesson) %></li>
            <% end %>
          </ul>
      </div>
    <% end %>
  </ul>
</div>

<%= link_to 'Add Section', new_section_path, class: 'btn btn-default' if current_user %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Epicodus</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Learn How to Program</a>
    </div>
    <div>
      <ul class="nav navbar-nav">
        <li><a href="/">Home</a></li>
        <li><a href="/users/sign_in">Sign In</a></li>
        <li><a href="/users/sign_up">Sign Up</a></li>
        <li><%= link_to 'Log Out', destroy_user_session_path, method: 'delete' %></li>
        <li><%= link_to 'User Info', user_path(current_user) if current_user %></li>
        <li><a><%= current_user.email if current_user %></a></li>
      </ul>

    </div>
  </div>
</nav>
<div class='container'>
  <%= flash[:notice] %>
  <%= flash[:alert] %>
  <%= yield %>
</div>

</body>
</html>

app/views/lessons/_form.html.erb
<%= form_for @lesson do |f| %>
  <div class='form-group'>
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control'%>
  </div>
  <div class='form-group'>
    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control', cols: 20, rows: 20 %>
  </div>
  <div class='form-group'>
    <%= f.label :section %>
     <%= f.collection_select(:section_id, Section.all, :id, :name ) %>
  </div>
  <%= f.submit %>
<% end %>

app/views/lessons/edit.html.erb
<%= render 'form' %>

app/views/lessons/index.html.erb
<h1>Learn How to Program </h1>

<% if @lessons.any? %>
  <ul>
    <% @lessons.each do |lesson| %>
      <li><%= link_to lesson.title, lesson_path(lesson) %></li>
    <% end %>
  </ul>
<% end%>

<%= link_to 'Add a New Lesson', new_lesson_path %>

app/views/lessons/show.html.erb
<h3><%= @lesson.title %></h3>

<p><%= @lesson.content %></p>
<% if current_user %>
  <%= link_to 'Edit', edit_lesson_path(@lesson) %> |
  <%= link_to 'Delete', lesson_path(@lesson), :data => {confirm: 'Are you sure?', method: 'delete'} if current_user %> |
<% end %>
<%= link_to 'Previous Lesson', lesson_path(@lesson.previous) %> |
<%= link_to 'Next Lesson', lesson_path(@lesson.next) %> |
<%= link_to 'Home', chapter_path(1) %>

app/views/sections/_form.html.erb
<%= form_for @section do |f| %>
  <div class='form-group'>
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control'%>
  </div>
  <%= f.submit %>
<% end %>

app/views/sections/new.html.erb
<%= render 'form' %>

app/views/sections/show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <%= @section.name %>
  </div>
  <ul>
    <% @section.lessons.each do |lesson| %>
      <li class="panel-body"><%= link_to lesson.title, lesson_path(lesson) %></li>
    <% end %>
  </ul>
</div>
<% if current_user %>
  <%= link_to 'Add Lesson', new_lesson_path  %> |
  <%= link_to 'Delete Section', section_path(@section), :data => {confirm: 'Are you sure?', method: 'delete'} if current_user %> |
<% end %>
<%= link_to 'Home', chapter_path(@section.chapter) %>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>